FROM centos：7.3.1611
MAINTAINER feiu <akwangj@126.com>
ENV TZ "Asia/Shanghai"
RUN yum install -y python-setuptools python-imaging python-ldap python-memcached MySQL-python wget
ADD /opt/saefile/
WORKDIR /opt/saefile/
RUN wget http://seafile-downloads.oss-cn-shanghai.aliyuncs.com/seafile-server_6.2.5_x86-64.tar.gz
RUN tar -zxvf seafile-server_6.2.5_x86-64.tar.gz && rm -Rf seafile-server_6.2.5_x86-64.tar.gz
WORKDIR /opt/saefile/seafile-server-6.2.5
RUN ./setup-seafile-mysql.sh
##报错，准备脚本
EXPOSE 8000 8002
ENTRYPOINT ['sh /opt/saefile/seafile-server-6.2.5/seafile.sh start']
